<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Review of General Linear Models - Week 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="P02 key_files/libs/clipboard/clipboard.min.js"></script>
<script src="P02 key_files/libs/quarto-html/quarto.js"></script>
<script src="P02 key_files/libs/quarto-html/popper.min.js"></script>
<script src="P02 key_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="P02 key_files/libs/quarto-html/anchor.min.js"></script>
<link href="P02 key_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="P02 key_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="P02 key_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="P02 key_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="P02 key_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Review of General Linear Models - Week 2</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><strong>Recall the <a href="https://www.jacksonheartstudy.org/">Jackson Heart Study</a> data from lecture. You can find data from clinic visits 1, 2, and 3 on Canvas.</strong></p>
<section id="a.-import-the-data-from-visit-1.-keep-only-subjid-sbp-age-hsgrad-diab3cat-and-bmi3cat.-make-sure-that-you-retain-only-the-complete-cases.-hint-research-how-to-exclude-observations-with-any-missing-responses." class="level4">
<h4 class="anchored" data-anchor-id="a.-import-the-data-from-visit-1.-keep-only-subjid-sbp-age-hsgrad-diab3cat-and-bmi3cat.-make-sure-that-you-retain-only-the-complete-cases.-hint-research-how-to-exclude-observations-with-any-missing-responses.">1a. Import the data from visit 1. Keep only subjid, sbp, age, HSgrad, diab3cat, and BMI3cat. Make sure that you retain only the complete cases. (Hint: research how to exclude observations with any missing responses.)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_sas</span>(<span class="st">"/Volumes/GoogleDrive/My Drive/STA6257/datasets/analysis1.sas7bdat"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subjid, sbp, age, HSgrad, diab3cat, BMI3cat) <span class="sc">%&gt;%</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="b.-create-dummy-variables-for-diabetic-status-diab3cat-and-health-status-based-on-body-mass-index-bmi3cat." class="level4">
<h4 class="anchored" data-anchor-id="b.-create-dummy-variables-for-diabetic-status-diab3cat-and-health-status-based-on-body-mass-index-bmi3cat.">1b. Create dummy variables for diabetic status (diab3cat) and health status based on body mass index (BMI3cat).</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(data, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">"diab3cat"</span>, <span class="st">"BMI3cat"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-systolic-blood-pressure-at-v1-sbp-as-a-function-of-age-years-education-hsgrad-1yes-0no-use-0-as-the-reference-group-diabetic-status-diab3cat-0non-diabetic-1pre-diabetic-2diabetic-use-0-as-the-reference-group-health-status-based-on-body-mass-index-bmi3cat-0poor-health-1intermediate-health-2ideal-health-and-all-possible-two-way-interactions." class="level4">
<h4 class="anchored" data-anchor-id="model-systolic-blood-pressure-at-v1-sbp-as-a-function-of-age-years-education-hsgrad-1yes-0no-use-0-as-the-reference-group-diabetic-status-diab3cat-0non-diabetic-1pre-diabetic-2diabetic-use-0-as-the-reference-group-health-status-based-on-body-mass-index-bmi3cat-0poor-health-1intermediate-health-2ideal-health-and-all-possible-two-way-interactions.">2. Model systolic blood pressure at V1 (sbp) as a function of age (years), education (HSgrad; 1=yes, 0=no; use 0 as the reference group), diabetic status (diab3cat; 0=non-diabetic, 1=pre-diabetic, 2=diabetic; use 0 as the reference group), health status based on body mass index (BMI3cat; 0=poor health, 1=intermediate health, 2=ideal health), and all possible two-way interactions.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>           age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>            diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, <span class="at">data=</span>data)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + 
    BMI3cat_2 + age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + 
    age:BMI3cat_1 + age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + 
    HSgrad:BMI3cat_1 + HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + 
    diab3cat_1:BMI3cat_2 + diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2, 
    data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.472  -9.836  -1.045   7.740  60.470 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          104.47748    5.23328  19.964  &lt; 2e-16 ***
age                    0.37913    0.08356   4.537 5.96e-06 ***
HSgrad                 2.42528    4.81331   0.504  0.61440    
diab3cat_1             0.68687    4.15256   0.165  0.86864    
diab3cat_2            17.08126    5.52162   3.094  0.00200 ** 
BMI3cat_1             -4.18025    4.09034  -1.022  0.30689    
BMI3cat_2            -13.89793    5.06646  -2.743  0.00613 ** 
age:HSgrad            -0.02300    0.07668  -0.300  0.76421    
age:diab3cat_1         0.02972    0.06094   0.488  0.62577    
age:diab3cat_2        -0.25441    0.08119  -3.134  0.00175 ** 
age:BMI3cat_1          0.12895    0.06095   2.116  0.03448 *  
age:BMI3cat_2          0.23278    0.07734   3.010  0.00264 ** 
HSgrad:diab3cat_1     -0.89779    2.06270  -0.435  0.66342    
HSgrad:diab3cat_2     -0.35413    2.34352  -0.151  0.87990    
HSgrad:BMI3cat_1      -5.55605    1.95406  -2.843  0.00450 ** 
HSgrad:BMI3cat_2      -0.31516    2.67130  -0.118  0.90609    
diab3cat_1:BMI3cat_1   0.40184    1.48069   0.271  0.78611    
diab3cat_1:BMI3cat_2  -3.10688    2.18979  -1.419  0.15608    
diab3cat_2:BMI3cat_1   0.07070    1.89780   0.037  0.97029    
diab3cat_2:BMI3cat_2   0.29205    3.78805   0.077  0.93855    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14.54 on 2604 degrees of freedom
Multiple R-squared:  0.1337,    Adjusted R-squared:  0.1274 
F-statistic: 21.15 on 19 and 2604 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-single-hypothesis-test-to-show-that-we-cannot-drop-all-of-the-interactions-at-the-same-time." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-single-hypothesis-test-to-show-that-we-cannot-drop-all-of-the-interactions-at-the-same-time.">3. Use the appropriate (single!) hypothesis test to show that we cannot drop all of the interactions <strong>at the same time</strong>.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2, <span class="at">data=</span>data)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2, m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   2617 560532                                  
2   2604 550739 13    9793.4 3.5619 1.426e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-health-status-based-on-body-mass-index." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-health-status-based-on-body-mass-index.">4. Use the appropriate hypothesis test to determine if we can drop the interaction between diabetic status and health status based on body mass index.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>           age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>           HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2, <span class="at">data=</span>data)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1   2608 551299                           
2   2604 550739  4    560.14 0.6621 0.6183</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-education." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-education.">5. Use the appropriate hypothesis test to determine if we can drop the interaction between diabetic status and education.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:BMI3cat_1 + HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + 
    diab3cat_1:BMI3cat_2 + diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1   2606 550781                           
2   2604 550739  2    41.761 0.0987  0.906</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-health-status-based-on-body-mass-index-and-education." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-health-status-based-on-body-mass-index-and-education.">6. Use the appropriate hypothesis test to determine if we can drop the interaction between health status based on body mass index and education.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + diab3cat_1:BMI3cat_1 + 
    diab3cat_1:BMI3cat_2 + diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1   2606 552564                              
2   2604 550739  2    1825.1 4.3146 0.01347 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-age-and-health-status-based-on-body-mass-index." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-age-and-health-status-based-on-body-mass-index.">7. Use the appropriate hypothesis test to determine if we can drop the interaction between age and health status based on body mass index.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + HSgrad:diab3cat_1 + 
    HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + HSgrad:BMI3cat_2 + 
    diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + diab3cat_2:BMI3cat_1 + 
    diab3cat_2:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1   2606 552940                                
2   2604 550739  2    2200.6 5.2024 0.005561 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-age." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-diabetic-status-and-age.">8. Use the appropriate hypothesis test to determine if we can drop the interaction between diabetic status and age.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>HSgrad <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:BMI3cat_1 + age:BMI3cat_2 + HSgrad:diab3cat_1 + 
    HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + HSgrad:BMI3cat_2 + 
    diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + diab3cat_2:BMI3cat_1 + 
    diab3cat_2:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1   2606 553336                                
2   2604 550739  2    2596.9 6.1393 0.002188 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-age-and-education." class="level4">
<h4 class="anchored" data-anchor-id="use-the-appropriate-hypothesis-test-to-determine-if-we-can-drop-the-interaction-between-age-and-education.">9. Use the appropriate hypothesis test to determine if we can drop the interaction between age and education.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> m1</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                diab3cat_1<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_1<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                diab3cat_2<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> diab3cat_2<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + age:BMI3cat_2 + 
    HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
Model 2: sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + BMI3cat_2 + 
    age:HSgrad + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:diab3cat_1 + HSgrad:diab3cat_2 + HSgrad:BMI3cat_1 + 
    HSgrad:BMI3cat_2 + diab3cat_1:BMI3cat_1 + diab3cat_1:BMI3cat_2 + 
    diab3cat_2:BMI3cat_1 + diab3cat_2:BMI3cat_2
  Res.Df    RSS Df Sum of Sq    F Pr(&gt;F)
1   2605 550758                         
2   2604 550739  1    19.033 0.09 0.7642</code></pre>
</div>
</div>
</section>
<section id="construct-a-final-model-that-does-not-have-the-interactions-you-deemed-insignificant-in-questions-4-through-9." class="level4">
<h4 class="anchored" data-anchor-id="construct-a-final-model-that-does-not-have-the-interactions-you-deemed-insignificant-in-questions-4-through-9.">10. Construct a “final model” that does not have the interactions you deemed insignificant in questions 4 through 9.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> age <span class="sc">+</span> HSgrad <span class="sc">+</span> diab3cat_1 <span class="sc">+</span> diab3cat_2 <span class="sc">+</span> BMI3cat_1 <span class="sc">+</span> BMI3cat_2 <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                age<span class="sc">:</span>diab3cat_1 <span class="sc">+</span> age<span class="sc">:</span>diab3cat_2 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> age<span class="sc">:</span>BMI3cat_2 <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                HSgrad<span class="sc">:</span>BMI3cat_1 <span class="sc">+</span> HSgrad<span class="sc">:</span>BMI3cat_2, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>data)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ age + HSgrad + diab3cat_1 + diab3cat_2 + BMI3cat_1 + 
    BMI3cat_2 + age:diab3cat_1 + age:diab3cat_2 + age:BMI3cat_1 + 
    age:BMI3cat_2 + HSgrad:BMI3cat_1 + HSgrad:BMI3cat_2, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.561  -9.936  -0.962   7.692  61.407 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      106.25710    2.83837  37.436  &lt; 2e-16 ***
age                0.35979    0.04656   7.728 1.55e-14 ***
HSgrad             0.50995    1.15936   0.440 0.660079    
diab3cat_1        -0.42300    3.21152  -0.132 0.895221    
diab3cat_2        16.72458    4.42123   3.783 0.000159 ***
BMI3cat_1         -4.29887    4.05388  -1.060 0.289046    
BMI3cat_2        -13.84030    4.95864  -2.791 0.005290 ** 
age:diab3cat_1     0.03161    0.05777   0.547 0.584262    
age:diab3cat_2    -0.25546    0.07618  -3.353 0.000809 ***
age:BMI3cat_1      0.13274    0.05781   2.296 0.021747 *  
age:BMI3cat_2      0.21018    0.07353   2.858 0.004292 ** 
HSgrad:BMI3cat_1  -5.52355    1.91355  -2.887 0.003927 ** 
HSgrad:BMI3cat_2   0.13121    2.56186   0.051 0.959158    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14.53 on 2611 degrees of freedom
Multiple R-squared:  0.1327,    Adjusted R-squared:  0.1288 
F-statistic:  33.3 on 12 and 2611 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="use-the-model-from-question-10-to-find-the-model-for-a-50-year-old-high-school-graduate." class="level4">
<h4 class="anchored" data-anchor-id="use-the-model-from-question-10-to-find-the-model-for-a-50-year-old-high-school-graduate.">11. Use the model from question 10 to find the model for a 50 year old high school graduate.</h4>
<p><span class="math display">\[\begin{align*}
\hat{y} =&amp; 124.75655 - 2.0035 \times \text{ pre-diabetic} + 3.95158 \times \text{diabetic} \\ &amp;- 5.41232 \times \text{ BMI}_{\text{moderate}} - 24.49051 \times \text{ BMI}_{\text{poor}}
\end{align*}\]</span></p>
<!--- 
Note: I am having R do the calculation for me with the stuff in backticks. 
      When I plugged in values, I put them where they would go after plugging in.
      (Algebraically, combining like terms.)
      e.g., the coefficient for age is multiplied by 50, which is just a scalar, 
      so it's added to the intercept. 
--->
</section>
<section id="use-the-model-from-question-11-to-interpret-the-slopes-corresponding-to-diabetic-status-and-health-status-as-defined-by-body-mass-index." class="level4">
<h4 class="anchored" data-anchor-id="use-the-model-from-question-11-to-interpret-the-slopes-corresponding-to-diabetic-status-and-health-status-as-defined-by-body-mass-index.">12. Use the model from question 11 to interpret the slopes corresponding to diabetic status and health status as defined by body mass index.</h4>
<ul>
<li><p>On average, the SBP of 50 year old pre-diabetics that have at least a high school education is 2 mmHg lower than that of non-diabetics.</p></li>
<li><p>On average, the SBP of 50 year old diabetics that have at least a high school education is 4 mmHg higher than that of non-diabetics.</p></li>
<li><p>On average, the SBP of 50 year olds in moderate health, as defined by BMI, and have at least a high school education is 5.4 mmHg lower than those in poor health as defined by BMI.</p></li>
<li><p>On average, the SBP of 50 year olds in ideal health, as defined by BMI, and have at least a high school education is 24.5 mmHg lower than those in poor health as defined by BMI.</p></li>
</ul>
</section>
<section id="use-the-model-from-question-10-to-find-the-model-for-a-pre-diabetic-person-that-is-in-poor-health." class="level4">
<h4 class="anchored" data-anchor-id="use-the-model-from-question-10-to-find-the-model-for-a-pre-diabetic-person-that-is-in-poor-health.">13. Use the model from question 10 to find the model for a pre-diabetic person that is in poor health.</h4>
<p><span class="math display">\[\begin{align*}
\hat{y} =&amp; 105.8341 + 0.35979 \times \text{ age} + 0.50995 \times \text{ HS grad}
\end{align*}\]</span></p>
</section>
<section id="use-the-model-from-question-13-to-interpret-the-slope-corresponding-to-age." class="level4">
<h4 class="anchored" data-anchor-id="use-the-model-from-question-13-to-interpret-the-slope-corresponding-to-age.">14. Use the model from question 13 to interpret the slope corresponding to age.</h4>
<ul>
<li><p>On average, for pre-diabetics in poor health, as defined by BMI, for a 1 year increase in age, we expect SBP to increase by 0.36 mmHg.</p></li>
<li><p>On average, for pre-diabetics in poor health, as defined by BMI, for a 5 year increase in age, we expect SBP to increase by 1.8 mmHg.</p></li>
<li><p>On average, for pre-diabetics in poor health, as defined by BMI, for a 10 year increase in age, we expect SBP to increase by 3.6 mmHg.</p></li>
</ul>
</section>
<section id="challenge-construct-a-visualization-to-help-with-interpreting-this-model.-systolic-blood-pressure-should-be-on-the-y-axis-age-should-be-on-the-x-axis.-you-choose-what-lines-to-create." class="level4">
<h4 class="anchored" data-anchor-id="challenge-construct-a-visualization-to-help-with-interpreting-this-model.-systolic-blood-pressure-should-be-on-the-y-axis-age-should-be-on-the-x-axis.-you-choose-what-lines-to-create.">15. (Challenge!) Construct a visualization to help with interpreting this model. Systolic blood pressure should be on the <em>y</em>-axis, age should be on the <em>x</em>-axis. You choose what lines to create.</h4>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>